/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author admin
 */
public class DetailedOverallStatisticsPanel extends javax.swing.JPanel {

    /**
     * Creates new form DetailedOverallStatisticsPanel
     */
    public DetailedOverallStatisticsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        matrixName = new javax.swing.JLabel();
        number = new javax.swing.JLabel();
        hitsLabel = new javax.swing.JLabel();
        hits = new javax.swing.JLabel();
        missesLabel = new javax.swing.JLabel();
        misses = new javax.swing.JLabel();
        successRateLabel = new javax.swing.JLabel();
        rate = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(450, 14));
        setPreferredSize(new java.awt.Dimension(450, 14));
        setLayout(new java.awt.GridLayout(1, 9));

        matrixName.setText("Matrix A: ");
        matrixName.setMinimumSize(new java.awt.Dimension(70, 14));
        matrixName.setName("");
        matrixName.setPreferredSize(new java.awt.Dimension(70, 14));
        add(matrixName);

        number.setText("0");
        add(number);

        hitsLabel.setLabelFor(hits);
        hitsLabel.setText("Hits: ");
        add(hitsLabel);

        hits.setText("0");
        add(hits);

        missesLabel.setLabelFor(misses);
        missesLabel.setText("Misses: ");
        add(missesLabel);

        misses.setText("0");
        add(misses);

        successRateLabel.setLabelFor(rate);
        successRateLabel.setText("Rate: ");
        add(successRateLabel);

        rate.setText("0");
        add(rate);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hits;
    private javax.swing.JLabel hitsLabel;
    private javax.swing.JLabel matrixName;
    private javax.swing.JLabel misses;
    private javax.swing.JLabel missesLabel;
    private javax.swing.JLabel number;
    private javax.swing.JLabel rate;
    private javax.swing.JLabel successRateLabel;
    // End of variables declaration//GEN-END:variables

    public void setMatrixName(String text) {
        matrixName.setText(text + ": ");
    }
    
    public void setNumber(long n) {
        number.setText(String.valueOf(n));
    }
    
    public void setHits(long n) {
        hits.setText(String.valueOf(n));
    }
    
    public void setMisses(long n) {
        misses.setText(String.valueOf(n));
    }
    
    public void setRate(String rate) {
        this.rate.setText(rate  + " %");
    }

}
