
package view;

import java.awt.GridBagConstraints;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Philip Becker-Ehmck
 */
public class OverallStatisticsPanel extends javax.swing.JPanel {

    /**
     * Creates new form OverallStatisticsPanel
     */
    public OverallStatisticsPanel() {
        initComponents();
        
        statisticsList = new ArrayList<DetailedOverallStatisticsPanel>();
        constraints = new GridBagConstraints();
        constraints.gridx = 1;
        constraints.gridy = 1;
        constraints.fill = constraints.HORIZONTAL;
        constraints.anchor = constraints.NORTHWEST;
        constraints.weightx = 1.0;
        constraints.weighty = 1.0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createTitledBorder("Overall Statistics"));
        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    // Varaibles declaration for dynamic GUI
    private List<DetailedOverallStatisticsPanel> statisticsList;
    private GridBagConstraints constraints;
    // End of variables declaration
    

    public void addStatistics(DetailedOverallStatisticsPanel detail) {
        add(detail, constraints);
        statisticsList.add(detail);
        constraints.gridy++;
    }

}
