/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.Pattern;
import java.awt.GridBagConstraints;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class PatternsPanel extends javax.swing.JPanel {

    private final GridBagConstraints constraints;

    /**
     * Creates new form patternsPanel
     */
    public PatternsPanel() {
        initComponents();
        constraints = new GridBagConstraints();
        constraints.gridx = 1;
        constraints.gridy = 1;
        constraints.fill = GridBagConstraints.HORIZONTAL;
        constraints.anchor = GridBagConstraints.NORTHWEST;
        constraints.weightx = 1.0;
        constraints.weighty = 1.0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        scrollPane = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Patterns"));
        setLayout(new java.awt.GridBagLayout());

        scrollPane.setBorder(null);

        panel.setLayout(new java.awt.GridBagLayout());
        scrollPane.setViewportView(panel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(scrollPane, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panel;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables

    public void addPattern(Pattern pattern) {
        PatternStatisticsPanel p = new PatternStatisticsPanel();
        p.setPattern(pattern);
        panel.add(p, constraints);

        constraints.gridy++;
    }

    public void removePatterns() {
        constraints.gridx = 1;
        constraints.gridy = 1;
        panel.removeAll();
    }

    public void fillSpace() {
        while (constraints.gridy < 5) {
            JPanel filler = new JPanel();
            filler.setMinimumSize(new java.awt.Dimension(450, 135));
            filler.setPreferredSize(new java.awt.Dimension(450, 135));
            panel.add(filler, constraints);
            constraints.gridy++;
        }
    }
}
