/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.Pattern;
import data.RelativeJump;
import java.awt.GridBagConstraints;
import java.text.NumberFormat;
import java.util.List;

/**
 *
 * @author Philip Becker-Ehmck
 */
public class PatternStatisticsPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatternsStatisticsPanel
     */
    public PatternStatisticsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        patternIDLabel = new javax.swing.JLabel();
        patternID = new javax.swing.JLabel();
        occurrencesLabel = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        patternSequence = new javax.swing.JTextArea();
        occurrences = new javax.swing.JLabel();
        statsPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMinimumSize(new java.awt.Dimension(450, 135));
        setName("");
        setPreferredSize(new java.awt.Dimension(450, 135));
        setLayout(new java.awt.GridBagLayout());

        patternIDLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        patternIDLabel.setText(" Pattern-ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(patternIDLabel, gridBagConstraints);

        patternID.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        patternID.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(patternID, gridBagConstraints);

        occurrencesLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        occurrencesLabel.setText(" Occurrences:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(occurrencesLabel, gridBagConstraints);

        scrollPane.setBorder(null);
        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrollPane.setOpaque(false);

        patternSequence.setColumns(20);
        patternSequence.setEditable(false);
        patternSequence.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        patternSequence.setLineWrap(true);
        patternSequence.setRows(5);
        patternSequence.setWrapStyleWord(true);
        patternSequence.setOpaque(false);
        patternSequence.setPreferredSize(new java.awt.Dimension(104, 19));
        scrollPane.setViewportView(patternSequence);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 3.0;
        add(scrollPane, gridBagConstraints);

        occurrences.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        occurrences.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(occurrences, gridBagConstraints);

        statsPanel.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText("Hits & misses of relative accesses?");
        jLabel2.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        statsPanel.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        add(statsPanel, gridBagConstraints);

        jLabel1.setText(" ???");
        jLabel1.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 3.0;
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel occurrences;
    private javax.swing.JLabel occurrencesLabel;
    private javax.swing.JLabel patternID;
    private javax.swing.JLabel patternIDLabel;
    private javax.swing.JTextArea patternSequence;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel statsPanel;
    // End of variables declaration//GEN-END:variables

    public void setPattern(Pattern p) {
        
        List<RelativeJump> jumps = p.getJumps();
        StringBuilder sb = new StringBuilder(" ");

        for (RelativeJump jump : jumps) {
            sb.append("(").append(jump.getX_move()).append("|").append(jump.getY_move()).append(") ");
        }
        
        PatternRepresentationPanel rep = new PatternRepresentationPanel(jumps);
        GridBagConstraints gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1;
        gridBagConstraints.anchor = GridBagConstraints.CENTER;
        // gridBagConstraints.fill = GridBagConstraints.BOTH;
        add(rep, gridBagConstraints);
        
        patternSequence.setText(sb.toString());        
        patternID.setText(String.valueOf(p.getPID()));
        occurrences.setText(NumberFormat.getInstance().format(p.getNumOccurrences()));
    }
}
