/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.GridBagConstraints;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author philip
 */
public class RelativeJumpPanel extends javax.swing.JPanel {

    /**
     * Creates new form RelativeJumpPanel
     */
    public RelativeJumpPanel() {
        initComponents();
        arrowList = new ArrayList<ArrowStatisticsPanel>();
        constraints = new GridBagConstraints();
        constraints.gridx = 1;
        constraints.gridy = 1;
        // constraints.fill = constraints.HORIZONTAL;
        // constraints.anchor = constraints.NORTHWEST;
        constraints.weightx = 1.0;
        constraints.weighty = 1.0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Relative Jumps", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N
        setLayout(new java.awt.GridLayout(2, 0));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private List<ArrowStatisticsPanel> arrowList;
    private GridBagConstraints constraints;
    
    void addArrowStatisticsPanel(ArrowStatisticsPanel arrow) {
        add(arrow, constraints);
        arrowList.add(arrow);
        if (constraints.gridx < 4) {
            constraints.gridx++;
        } else {
            constraints.gridy++;
            constraints.gridx = 1;
        }
    }

    void removeArrowStatistics() {
        for (ArrowStatisticsPanel arrow: arrowList) {
            remove(arrow);
        }
    }
}
