/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.DecimalFormat;
import java.text.NumberFormat;

/**
 *
 * @author Philip Becker-Ehmck
 */
public class StatisticsPanel extends javax.swing.JPanel {

    /**
     * Creates new form StatisticsPanel
     */
    public StatisticsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emptyLabel = new javax.swing.JLabel();
        hitsLabel = new javax.swing.JLabel();
        missesLabel = new javax.swing.JLabel();
        rateLabel = new javax.swing.JLabel();
        overallLabel = new javax.swing.JLabel();
        hitsOverall = new javax.swing.JLabel();
        missesOverall = new javax.swing.JLabel();
        rateOverall = new javax.swing.JLabel();
        nameMatrix = new javax.swing.JLabel();
        hitsMatrix = new javax.swing.JLabel();
        missesMatrix = new javax.swing.JLabel();
        rateMatrix = new javax.swing.JLabel();
        loadLabel = new javax.swing.JLabel();
        hitsLoad = new javax.swing.JLabel();
        missesLoad = new javax.swing.JLabel();
        rateLoad = new javax.swing.JLabel();
        storeLabel = new javax.swing.JLabel();
        hitsStore = new javax.swing.JLabel();
        missesStore = new javax.swing.JLabel();
        rateStore = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Overall Statistics", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        setMinimumSize(new java.awt.Dimension(450, 50));
        setPreferredSize(new java.awt.Dimension(450, 50));
        setLayout(new java.awt.GridLayout(5, 5));
        add(emptyLabel);

        hitsLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hitsLabel.setText("Hits");
        add(hitsLabel);

        missesLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        missesLabel.setText("Misses");
        add(missesLabel);

        rateLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rateLabel.setText("Success Rate");
        add(rateLabel);

        overallLabel.setText("Overall:");
        add(overallLabel);

        hitsOverall.setText("0");
        add(hitsOverall);

        missesOverall.setText("0");
        add(missesOverall);

        rateOverall.setText("0");
        add(rateOverall);

        nameMatrix.setText("Matrix:");
        add(nameMatrix);

        hitsMatrix.setText("0");
        add(hitsMatrix);

        missesMatrix.setText("0");
        add(missesMatrix);

        rateMatrix.setText("0");
        add(rateMatrix);

        loadLabel.setText("Load:");
        add(loadLabel);

        hitsLoad.setText("0");
        add(hitsLoad);

        missesLoad.setText("0");
        add(missesLoad);

        rateLoad.setText("0");
        add(rateLoad);

        storeLabel.setText("Store:");
        add(storeLabel);

        hitsStore.setText("0");
        add(hitsStore);

        missesStore.setText("0");
        add(missesStore);

        rateStore.setText("0");
        add(rateStore);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emptyLabel;
    private javax.swing.JLabel hitsLabel;
    private javax.swing.JLabel hitsLoad;
    private javax.swing.JLabel hitsMatrix;
    private javax.swing.JLabel hitsOverall;
    private javax.swing.JLabel hitsStore;
    private javax.swing.JLabel loadLabel;
    private javax.swing.JLabel missesLabel;
    private javax.swing.JLabel missesLoad;
    private javax.swing.JLabel missesMatrix;
    private javax.swing.JLabel missesOverall;
    private javax.swing.JLabel missesStore;
    private javax.swing.JLabel nameMatrix;
    private javax.swing.JLabel overallLabel;
    private javax.swing.JLabel rateLabel;
    private javax.swing.JLabel rateLoad;
    private javax.swing.JLabel rateMatrix;
    private javax.swing.JLabel rateOverall;
    private javax.swing.JLabel rateStore;
    private javax.swing.JLabel storeLabel;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @param hits hits across all matrices
     * @param misses misses across all matrices
     */
    public void setOverallStatistics(long hits, long misses) {
        hitsOverall.setText(NumberFormat.getInstance().format(hits));
        missesOverall.setText(NumberFormat.getInstance().format(misses));
        DecimalFormat f = new DecimalFormat("#0.00");
        rateOverall.setText(f.format((double) hits / (double) (hits + misses) * 100) + " %");
    }

    /**
     *
     * @param load hits, misses of load accesses
     * @param store hits, misses of store acesses
     * @param name name of the matrix
     */
    public void setMatrixStatistics(int[] load, int[] store, String name) {
        long overallHits = load[0] + store[0];
        long overallMisses = load[1] + store[1];
        DecimalFormat f = new DecimalFormat("#0.00");

        nameMatrix.setText(name + ":");
        hitsMatrix.setText(NumberFormat.getInstance().format(overallHits));
        missesMatrix.setText(NumberFormat.getInstance().format(overallMisses));
        if ((overallHits + overallMisses) == 0) {
            rateMatrix.setText("0.00 %");
        } else {
            rateMatrix.setText(f.format((double) overallHits / (double) (overallHits + overallMisses) * 100) + " %");
        }

        hitsLoad.setText(NumberFormat.getInstance().format(load[0]));
        missesLoad.setText(NumberFormat.getInstance().format(load[1]));
        if ((load[0] + load[1]) == 0) {
            rateLoad.setText("0.00 %");
        } else {
            rateLoad.setText(f.format((double) load[0] / (double) (load[0] + load[1]) * 100) + " %");
        }

        hitsStore.setText(NumberFormat.getInstance().format(store[0]));
        missesStore.setText(NumberFormat.getInstance().format(store[1]));
        if ((store[0] + store[1]) == 0) {
            rateStore.setText("0.00 %");
        } else {
            rateStore.setText(f.format((double) store[0] / (double) (store[0] + store[1]) * 100) + " %");
        }
    }
}
