/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.DecimalFormat;
import java.text.NumberFormat;

/**
 *
 * @author Philip Becker-Ehmck
 */
public class StatisticsPanel extends javax.swing.JPanel {

    /**
     * Creates new form StatisticsPanel
     */
    public StatisticsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hitsOverall = new javax.swing.JLabel();
        missesOverall = new javax.swing.JLabel();
        rateOverall = new javax.swing.JLabel();
        nameMatrix = new javax.swing.JLabel();
        hitsMatrix = new javax.swing.JLabel();
        missesMatrix = new javax.swing.JLabel();
        rateMatrix = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Overall Statistics", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        setMinimumSize(new java.awt.Dimension(450, 50));
        setPreferredSize(new java.awt.Dimension(450, 50));
        setLayout(new java.awt.GridLayout(3, 5));
        add(jLabel5);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Hits");
        add(jLabel2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Misses");
        add(jLabel1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Success Rate");
        add(jLabel3);

        jLabel7.setText("Overall:");
        add(jLabel7);

        hitsOverall.setText("0");
        add(hitsOverall);

        missesOverall.setText("0");
        add(missesOverall);

        rateOverall.setText("0");
        add(rateOverall);

        nameMatrix.setText("Matrix:");
        add(nameMatrix);

        hitsMatrix.setText("0");
        add(hitsMatrix);

        missesMatrix.setText("0");
        add(missesMatrix);

        rateMatrix.setText("0");
        add(rateMatrix);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hitsMatrix;
    private javax.swing.JLabel hitsOverall;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel missesMatrix;
    private javax.swing.JLabel missesOverall;
    private javax.swing.JLabel nameMatrix;
    private javax.swing.JLabel rateMatrix;
    private javax.swing.JLabel rateOverall;
    // End of variables declaration//GEN-END:variables

    public void setOverallStatistics(long hits, long misses) {
        hitsOverall.setText(NumberFormat.getInstance().format(hits));
        missesOverall.setText(NumberFormat.getInstance().format(misses));
        DecimalFormat f = new DecimalFormat("#0.00");
        rateOverall.setText(f.format((double) hits / (double) (hits + misses) * 100) + " %");
    }
    
    public void setMatrixStatistics(long hits, long misses, int number) {
        nameMatrix.setText("Matrix " + ++number + ":");
        hitsMatrix.setText(NumberFormat.getInstance().format(hits));
        missesMatrix.setText(NumberFormat.getInstance().format(misses));
        DecimalFormat f = new DecimalFormat("#0.00");
        rateMatrix.setText(f.format((double) hits / (double) (hits + misses) * 100)+ " %");
    }

}
